=== SamWieHTWG/web-api/components/config/meta-data/CncParaDesc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ISG Stuttgart -->
<xs:schema xmlns="https://www.isg-stuttgart.de/kernel/CncParaDesc" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="https://www.isg-stuttgart.de/kernel/CncParaDesc" version="1.0">
  <xs:simpleType name="datatype" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ADDRESS"/>
      <xs:enumeration value="BOOLEAN"/>
      <xs:enumeration value="CHAR"/>
      <xs:enumeration value="REAL64"/>
      <xs:enumeration value="SGN08"/>
      <xs:enumeration value="SGN16"/>
      <xs:enumeration value="SGN32"/>
      <xs:enumeration value="SGN64"/>
      <xs:enumeration value="STRING"/>
      <xs:enumeration value="STRUCT"/>
      <xs:enumeration value="UNS08"/>
      <xs:enumeration value="UNS16"/>
      <xs:enumeration value="UNS32"/>
      <xs:enumeration value="UNS64"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="language" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="en"/>
      <xs:enumeration value="de"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Unit" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id" minOccurs="1" maxOccurs="1" type="xs:ID"/>
              <xs:element name="Text" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="Language" type="language"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="TextASCII" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="Language" type="language"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id" minOccurs="1" maxOccurs="1" type="xs:ID"/>
              <xs:element name="Name" minOccurs="0" maxOccurs="1" type="xs:string"/>
              <xs:element name="ShortDescription" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Text" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="Language" type="language"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="LongDescription" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Text" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="Language" type="language"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Quantity" minOccurs="0" maxOccurs="1" type="xs:string"/>
              <xs:element name="Units" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Unit" minOccurs="0" maxOccurs="unbounded" type="xs:IDREF"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="DefaultValue" minOccurs="1" maxOccurs="1" type="xs:string"/>
              <xs:element name="Range" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Text" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="Language" type="language"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Type" minOccurs="1" maxOccurs="1" type="datatype"/>
              <xs:element name="Bitfield" minOccurs="0" maxOccurs="1" type="xs:nonNegativeInteger"/>
              <xs:element name="MaxStringLength" minOccurs="0" maxOccurs="1" type="xs:nonNegativeInteger"/>
              <xs:element name="SymbolValues" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="SymbolValue" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Name" minOccurs="1" maxOccurs="1" type="xs:string"/>
                          <xs:element name="Value" minOccurs="0" maxOccurs="1" type="xs:integer"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="MaxNumber" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ArrayIndex" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:nonNegativeInteger">
                            <xs:attribute name="No" type="xs:nonNegativeInteger"/>
                            <xs:attribute name="Name" type="xs:string"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Encrypted" minOccurs="1" maxOccurs="1" type="xs:boolean"/>
              <xs:element name="ChangeRequiresRestart" minOccurs="1" maxOccurs="1" type="xs:boolean"/>
              <xs:element name="Help" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Link" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="Language" type="language"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Section" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Text" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="Language" type="language"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded" type="xs:IDREF"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SamWieHTWG/web-api/components/config/meta-data/splitted/CncParaDesc-ZERO.xml
<?xml version='1.0' encoding='UTF-8'?>
<Parameters xmlns="https://www.isg-stuttgart.de/kernel/CncParaDesc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CncParaDesc.xsd">
  <Unit>
    <Id>UNIT_0_1_MICROMETER</Id>
    <Text Language="en">0.1µm</Text>
    <Text Language="de">0.1µm</Text>
    <TextASCII Language="en">0.1um</TextASCII>
    <TextASCII Language="de">0.1um</TextASCII>
  </Unit>
  <Unit>
    <Id>UNIT_0_1_MILLIDEGREE</Id>
    <Text Language="en">0.1m°</Text>
    <Text Language="de">0.1m°</Text>
    <TextASCII Language="en">0.1mdeg</TextASCII>
    <TextASCII Language="de">0.1mdeg</TextASCII>
  </Unit>
  <Unit>
    <Id>UNIT_NONE</Id>
    <Text Language="en">-</Text>
    <Text Language="de">-</Text>
    <TextASCII Language="en">-</TextASCII>
    <TextASCII Language="de">-</TextASCII>
  </Unit>
  <Unit>
    <Id>UNIT_SYMBOL</Id>
    <Text Language="en">-</Text>
    <Text Language="de">-</Text>
    <TextASCII Language="en">-</TextASCII>
    <TextASCII Language="de">-</TextASCII>
  </Unit>
  <Parameter>
    <Id>P-ZERO-00001</Id>
    <Name>g53_verfuegbar</Name>
    <ShortDescription>
      <Text Language="en">Deselecting zero offsets</Text>
      <Text Language="de">Abwahl von Nullpunktverschiebungen</Text>
    </ShortDescription>
    <LongDescription>
      <Text Language="en">This parameter allows the use of the G53 data record to define an additional offset data record.</Text>
      <Text Language="de">Der Parameter ermöglicht die Verwendung des G53-Datensatzes für die Definition eines zusätzlichen Verschiebungsdatensatzes.</Text>
    </LongDescription>
    <Quantity>SYMBOL</Quantity>
    <DefaultValue>FALSE</DefaultValue>
    <Range>
      <Text Language="en">0/1</Text>
      <Text Language="de">0/1</Text>
    </Range>
    <Type>BOOLEAN</Type>
    <SymbolValues>
      <SymbolValue>
        <Name>FALSE</Name>
        <Value>0</Value>
      </SymbolValue>
      <SymbolValue>
        <Name>TRUE</Name>
        <Value>1</Value>
      </SymbolValue>
    </SymbolValues>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
    <Help>
      <Link Language="en">https://www.isg-stuttgart.de/fileadmin/kernel/kernel-html/en-GB/index.html#103718027</Link>
      <Link Language="de">https://www.isg-stuttgart.de/fileadmin/kernel/kernel-html/de-DE/index.html#103718027</Link>
    </Help>
  </Parameter>
  <Parameter>
    <Id>P-ZERO-00002</Id>
    <Name>default_index</Name>
    <ShortDescription>
      <Text Language="en">Default setting of zero offsets</Text>
      <Text Language="de">Defaulteinstellung von Nullpunktverschiebungen</Text>
    </ShortDescription>
    <LongDescription>
      <Text Language="en">This parameter defines what zero offsets (index) should be automatically active after program start-up.</Text>
      <Text Language="de">Über diesen Parameter kann bestimmt werden, welche Nullpunktverschiebung (Index) nach Programmstart automatisch aktiv sein soll.</Text>
    </LongDescription>
    <DefaultValue>0</DefaultValue>
    <Range>
      <Text Language="en">0 ... 96 (number of zero offset groups: 97, application-specific)</Text>
      <Text Language="de">0 ... 96 (Anzahl der Nullpunktverschiebungsgruppen: 97, applikationsspezifisch)</Text>
    </Range>
    <Type>UNS16</Type>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
    <Help>
      <Link Language="en">https://www.isg-stuttgart.de/fileadmin/kernel/kernel-html/en-GB/index.html#103719563</Link>
      <Link Language="de">https://www.isg-stuttgart.de/fileadmin/kernel/kernel-html/de-DE/index.html#103719563</Link>
    </Help>
  </Parameter>
  <Parameter>
    <Id>P-ZERO-00003</Id>
    <Name>np_grp[].achse[].versch</Name>
    <ShortDescription>
      <Text Language="en">Zero offset</Text>
      <Text Language="de">Nullpunktverschiebung</Text>
    </ShortDescription>
    <LongDescription>
      <Text Language="en">An offset parameter is reserved for every axis in every zero offset group.</Text>
      <Text Language="de">Pro Nullpunktverschiebungsgruppe ist für jede Achse ein Versatzparameter reserviert.</Text>
    </LongDescription>
    <Quantity>LENGTH</Quantity>
    <Units>
      <Unit>UNIT_0_1_MICROMETER</Unit>
      <Unit>UNIT_0_1_MILLIDEGREE</Unit>
    </Units>
    <DefaultValue>0</DefaultValue>
    <Range>
      <Text Language="en">MIN(SGN32) &lt; versch &lt; MAX(SGN32)</Text>
      <Text Language="de">MIN(SGN32) &lt; versch &lt; MAX(SGN32)</Text>
    </Range>
    <Type>SGN32</Type>
    <MaxNumber>
      <ArrayIndex No="0" Name="np_grp">97</ArrayIndex>
      <ArrayIndex No="1" Name="achse">32</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
    <Help>
      <Link Language="en">https://www.isg-stuttgart.de/fileadmin/kernel/kernel-html/en-GB/index.html#103724043</Link>
      <Link Language="de">https://www.isg-stuttgart.de/fileadmin/kernel/kernel-html/de-DE/index.html#103724043</Link>
    </Help>
  </Parameter>
  <Parameter>
    <Id>P-ZERO-00004</Id>
    <Name>np_grp[].achse[].inaktiv</Name>
    <ShortDescription>
      <Text Language="en">Axis-specific activation</Text>
      <Text Language="de">Achsspezifische Aktivierung</Text>
    </ShortDescription>
    <LongDescription>
      <Text Language="en">In every zero point data block, setting the inactive code defines the axes in which the offset is to be included in the calculation or not. As a result, individual axis offsets can be hidden in specific zero offsets.If the inactive code is notassigned or is assigned with zero, the axis offset continues to remain valid. If they are set to TRUE, they are inactive, see also [PROG// Zero offsets].</Text>
      <Text Language="de">Für jeden Nullpunktdatensatz kann durch Setzen der inaktiv-Kennung bestimmt werden, für welche Achsen der Versatz eingerechnet bzw. nicht eingerechnet werden soll. Dadurch können einzelne Achsversätze bestimmter Nullpunktverschiebungen ausgeblendet werden.Wird die Inaktiv-Kennung nicht oder mit Null belegt, sind die Achsversätze weiterhin gültig. Bei TRUE sind sie inaktiv gesetzt, siehe auch [PROG// Nullpunktverschiebungen].</Text>
    </LongDescription>
    <Quantity>SYMBOL</Quantity>
    <DefaultValue>FALSE</DefaultValue>
    <Range>
      <Text Language="en">0/1</Text>
      <Text Language="de">0/1</Text>
    </Range>
    <Type>BOOLEAN</Type>
    <SymbolValues>
      <SymbolValue>
        <Name>FALSE</Name>
        <Value>0</Value>
      </SymbolValue>
      <SymbolValue>
        <Name>TRUE</Name>
        <Value>1</Value>
      </SymbolValue>
    </SymbolValues>
    <MaxNumber>
      <ArrayIndex No="0" Name="np_grp">97</ArrayIndex>
      <ArrayIndex No="1" Name="achse">32</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
    <Help>
      <Link Language="en">https://www.isg-stuttgart.de/fileadmin/kernel/kernel-html/en-GB/index.html#103725579</Link>
      <Link Language="de">https://www.isg-stuttgart.de/fileadmin/kernel/kernel-html/de-DE/index.html#103725579</Link>
    </Help>
  </Parameter>
  <Section>
    <Name>
      <Text Language="en">General parameter</Text>
      <Text Language="de">Allgemeine Parameter</Text>
    </Name>
    <Parameter>P-ZERO-00002</Parameter>
    <Parameter>P-ZERO-00001</Parameter>
  </Section>
  <Section>
    <Name>
      <Text Language="en">Offsets --- test ---</Text>
      <Text Language="de">Verschiebungen  --- test ---</Text>
    </Name>
    <Parameter>P-ZERO-00004</Parameter>
    <Parameter>P-ZERO-00003</Parameter>
  </Section>
</Parameters>

=== SamWieHTWG/web-api/components/config/meta-data/splitted/CncParaDesc-HWCF.xml
<?xml version='1.0' encoding='UTF-8'?>
<Parameters xmlns="https://www.isg-stuttgart.de/kernel/CncParaDesc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CncParaDesc.xsd">
  <Unit>
    <Id>UNIT_NONE</Id>
    <Text Language="en">-</Text>
    <Text Language="de">-</Text>
    <TextASCII Language="en">-</TextASCII>
    <TextASCII Language="de">-</TextASCII>
  </Unit>
  <Unit>
    <Id>UNIT_SYMBOL</Id>
    <Text Language="en">-</Text>
    <Text Language="de">-</Text>
    <TextASCII Language="en">-</TextASCII>
    <TextASCII Language="de">-</TextASCII>
  </Unit>
  <Parameter>
    <Id>P-HWCF-00001</Id>
    <Name>device[].type</Name>
    <Quantity>SYMBOL</Quantity>
    <DefaultValue/>
    <Type>STRING</Type>
    <SymbolValues>
      <SymbolValue>
        <Name>HW_DEVICE_NONE</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_8ACHS_V2_ISG</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_SERCOS_IPK</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_SERCOS_AUT_PCI</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_SERCOS_IAM</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_SERCOS_ACD_PCI</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_SERCOS_BECK_PCI_1CH</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_SERCOS_BECK_PCI_2CH</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_STEP_MOTOR_RUW</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_PK40_CIM</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_8ACHS_V3_ISG_PCI</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_RUW_MCU_3T_PCI</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_KUKA_DSE</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_CANOPEN</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_SIMULATION</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_SERCOS_HIL_PCI_CIF50SCEB</Name>
      </SymbolValue>
      <SymbolValue>
        <Name>HW_DEVICE_ACD_MFC01</Name>
      </SymbolValue>
    </SymbolValues>
    <MaxNumber>
      <ArrayIndex No="0" Name="device">4</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
  <Parameter>
    <Id>P-HWCF-00002</Id>
    <Name>device[].name</Name>
    <DefaultValue/>
    <Type>STRING</Type>
    <MaxStringLength>127</MaxStringLength>
    <MaxNumber>
      <ArrayIndex No="0" Name="device">4</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
  <Parameter>
    <Id>P-HWCF-00003</Id>
    <Name>device[].address</Name>
    <DefaultValue/>
    <Type>ADDRESS</Type>
    <MaxNumber>
      <ArrayIndex No="0" Name="device">4</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
  <Parameter>
    <Id>P-HWCF-00004</Id>
    <Name>device[].length</Name>
    <DefaultValue/>
    <Type>UNS32</Type>
    <MaxNumber>
      <ArrayIndex No="0" Name="device">4</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
  <Parameter>
    <Id>P-HWCF-00005</Id>
    <Name>device[].irq</Name>
    <DefaultValue/>
    <Type>UNS16</Type>
    <MaxNumber>
      <ArrayIndex No="0" Name="device">4</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
  <Parameter>
    <Id>P-HWCF-00006</Id>
    <Name>device[].baudrate</Name>
    <DefaultValue/>
    <Type>UNS16</Type>
    <MaxNumber>
      <ArrayIndex No="0" Name="device">4</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
  <Parameter>
    <Id>P-HWCF-00007</Id>
    <Name>device[].prog_param[]</Name>
    <DefaultValue/>
    <Type>UNS32</Type>
    <MaxNumber>
      <ArrayIndex No="0" Name="device">4</ArrayIndex>
      <ArrayIndex No="1" Name="prog_param">9</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
</Parameters>

=== SamWieHTWG/web-api/components/config/meta-data/splitted/CncParaDesc-CMLD.xml
<?xml version='1.0' encoding='UTF-8'?>
<Parameters xmlns="https://www.isg-stuttgart.de/kernel/CncParaDesc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CncParaDesc.xsd">
  <Unit>
    <Id>UNIT_NONE</Id>
    <Text Language="en">-</Text>
    <Text Language="de">-</Text>
    <TextASCII Language="en">-</TextASCII>
    <TextASCII Language="de">-</TextASCII>
  </Unit>
  <Parameter>
    <Id>P-CMLD-00001</Id>
    <Name>ddl[].token</Name>
    <DefaultValue/>
    <Type>STRING</Type>
    <MaxStringLength>9</MaxStringLength>
    <MaxNumber>
      <ArrayIndex No="0" Name="ddl">48</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
  <Parameter>
    <Id>P-CMLD-00002</Id>
    <Name>ddl[].type</Name>
    <DefaultValue>0</DefaultValue>
    <Type>UNS16</Type>
    <MaxNumber>
      <ArrayIndex No="0" Name="ddl">48</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
  <Parameter>
    <Id>P-CMLD-00003</Id>
    <Name>ddl[].index</Name>
    <DefaultValue>0</DefaultValue>
    <Type>UNS16</Type>
    <MaxNumber>
      <ArrayIndex No="0" Name="ddl">48</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
  <Parameter>
    <Id>P-CMLD-00004</Id>
    <Name>ddl[].default</Name>
    <DefaultValue/>
    <Type>STRING</Type>
    <MaxStringLength>23</MaxStringLength>
    <MaxNumber>
      <ArrayIndex No="0" Name="ddl">48</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
  </Parameter>
</Parameters>

=== SamWieHTWG/web-api/components/config/meta-data/splitted/CncParaDesc-CLMP.xml
<?xml version='1.0' encoding='UTF-8'?>
<Parameters xmlns="https://www.isg-stuttgart.de/kernel/CncParaDesc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CncParaDesc.xsd">
  <Unit>
    <Id>UNIT_0_1_MICROMETER</Id>
    <Text Language="en">0.1µm</Text>
    <Text Language="de">0.1µm</Text>
    <TextASCII Language="en">0.1um</TextASCII>
    <TextASCII Language="de">0.1um</TextASCII>
  </Unit>
  <Unit>
    <Id>UNIT_0_1_MILLIDEGREE</Id>
    <Text Language="en">0.1m°</Text>
    <Text Language="de">0.1m°</Text>
    <TextASCII Language="en">0.1mdeg</TextASCII>
    <TextASCII Language="de">0.1mdeg</TextASCII>
  </Unit>
  <Parameter>
    <Id>P-CLMP-00001</Id>
    <Name>pzv_grp[].achse[].versatz</Name>
    <ShortDescription>
      <Text Language="en">Axis-specific clamp position offset</Text>
      <Text Language="de">Achsspezifischer Platzversatz</Text>
    </ShortDescription>
    <LongDescription>
      <Text Language="en">An offset parameter is reserved for each axis in each clamp position offset group.</Text>
      <Text Language="de">Pro Platzversatzgruppe ist für jede Achse ein Versatzparameter reserviert.</Text>
    </LongDescription>
    <Quantity>LENGTH</Quantity>
    <Units>
      <Unit>UNIT_0_1_MICROMETER</Unit>
      <Unit>UNIT_0_1_MILLIDEGREE</Unit>
    </Units>
    <DefaultValue>0</DefaultValue>
    <Range>
      <Text Language="en">MIN(SGN32) ≤ versatz ≤ MAX(SGN32)</Text>
      <Text Language="de">MIN(SGN32) ≤ versatz ≤ MAX(SGN32)</Text>
    </Range>
    <Type>SGN32</Type>
    <MaxNumber>
      <ArrayIndex No="0" Name="pzv_grp">150</ArrayIndex>
      <ArrayIndex No="1" Name="achse">32</ArrayIndex>
    </MaxNumber>
    <Encrypted>false</Encrypted>
    <ChangeRequiresRestart>false</ChangeRequiresRestart>
    <Help>
      <Link Language="en">https://www.isg-stuttgart.de/fileadmin/kernel/kernel-html/en-GB/index.html#109093643</Link>
      <Link Language="de">https://www.isg-stuttgart.de/fileadmin/kernel/kernel-html/de-DE/index.html#109093643</Link>
    </Help>
  </Parameter>
  <Section>
    <Name>
      <Text Language="en">Clamp position offset groups</Text>
      <Text Language="de">Platzversatz Gruppen</Text>
    </Name>
    <Parameter>P-CLMP-00001</Parameter>
  </Section>
</Parameters>
